package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"

	"proxmox-license-proxy/internal/app"
	"proxmox-license-proxy/internal/fileio"
	"proxmox-license-proxy/internal/registry"
	"proxmox-license-proxy/internal/subscription"
)

var (
	licenseAddProduct string
	licenseAddName    string
	licenseAddDue     string
	licenseAddStatus  string
	licenseAddForce   bool

	licenseSetDue string

	licenseExportOut string
	licenseImportIn  string

	licenseRemoveYes bool

	licenseGenProduct string
	licenseGenLevel   string
	licenseGenSockets string
	licenseGenYes     bool
)

// labSubscriptionBanner is printed before generating a key to make absolutely
// sure the user understands this is never a production subscription.
const labSubscriptionBanner = `
============================================================
  LAB SUBSCRIPTION - NOT FOR PRODUCTION
============================================================
  Generated by proxmox-license-proxy for PRIVATE / INTERNAL
  test environments only. This is NOT a real Proxmox
  subscription. Using it on a production host bypasses a
  commercial subscription.

  Note: this only fakes the local subscription STATUS. It does
  NOT unlock the Proxmox enterprise apt repository, which is
  gated server-side by Proxmox.

  Running Proxmox in production? Buy a subscription:
  https://www.proxmox.com
============================================================
`

// store opens the registry store from the loaded settings.
func store() *registry.Store {
	return registry.NewStore(settings.RegistryFile)
}

// selectLicenseKey interactively picks one registered subscription key for an
// action (verb), labelling each with its product and status. Returns "" if there
// is nothing to act on or the user picked nothing.
func selectLicenseKey(verb string) (string, error) {
	licenses, err := store().ListLicenses()
	if err != nil {
		return "", err
	}
	if len(licenses) == 0 {
		fmt.Printf("no subscriptions to %s\n", verb)
		return "", nil
	}
	opts := make([]huh.Option[string], len(licenses))
	for i, l := range licenses {
		label := l.Key
		if l.ProductName != "" {
			label += "  " + l.ProductName
		}
		label += fmt.Sprintf("  [%s]", l.Status)
		opts[i] = huh.NewOption(label, l.Key)
	}
	var key string
	err = promptSelect("Select a subscription to "+verb, &key, opts...)
	return key, err
}

// resolveLicenseKeyArg returns the key argument, or opens an interactive picker
// when none is given on a terminal, so admins rarely need to copy keys.
func resolveLicenseKeyArg(args []string, verb string) (string, error) {
	if len(args) == 1 {
		return args[0], nil
	}
	if interactiveTTY() {
		return selectLicenseKey(verb)
	}
	return "", fmt.Errorf("no key given (pass a subscription key, or run on a terminal to pick interactively)")
}

var licenseCmd = &cobra.Command{
	Use:     "subscription",
	Aliases: []string{"license", "sub"},
	Short:   "Manage subscription keys in the registry",
	Long: "Manage subscription keys in the registry. Run without a subcommand on a\n" +
		"terminal to open a guided menu (generate / list / show / rm / ...).",
	RunE: menuOrHelp,
}

var licenseAddCmd = &cobra.Command{
	Use:   "add [key]",
	Short: "Add an existing lab subscription key (use `generate` to mint a new one)",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var key string
		if len(args) == 1 {
			key = args[0]
		} else if interactiveTTY() {
			fmt.Println("Tip: to mint a brand-new lab key instead, run `subscription generate`.")
			if err := promptInput("Subscription key to add", "e.g. pbsc-1ab879865b", &key); err != nil {
				return err
			}
		}
		if key == "" {
			return fmt.Errorf("no key given (pass a subscription key, run on a terminal to enter one, or use `subscription generate`)")
		}
		lic, err := app.New(store()).AddLicense(app.AddLicenseInput{
			Key:         key,
			Product:     licenseAddProduct,
			ProductName: licenseAddName,
			StatusRaw:   licenseAddStatus,
			NextDueDate: licenseAddDue,
			Force:       licenseAddForce,
		})
		if err != nil {
			return err
		}
		fmt.Printf("added %s (%s, status=%s, due %s)\n", lic.Key, lic.ProductName, lic.Status, lic.NextDueDate)
		return nil
	},
}

var licenseGenerateCmd = &cobra.Command{
	Use:     "generate",
	Aliases: []string{"gen"},
	Short:   "Generate and register a lab-only subscription key (never for production)",
	Long: "Generate a format-valid Proxmox key that is deliberately marked as a lab key:\n" +
		"the key carries a visible \"1ab\" (lab) signature and its product name is tagged\n" +
		"with the proxmox-license-proxy origin, so its lab status shows in the Proxmox UI.",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Fprint(cmd.OutOrStdout(), labSubscriptionBanner)
		product, level, sockets, err := resolveGenChoices(cmd)
		if err != nil {
			return err
		}
		if err := confirm(cmd, licenseGenYes,
			"I understand this key is LAB-ONLY and must never be used in production. Continue?"); err != nil {
			return err
		}
		lic, err := app.New(store()).GenerateLicense(product, level, sockets, true)
		if err != nil {
			return err
		}
		fmt.Printf("\n  key:     %s\n", lic.Key)
		fmt.Printf("  product: %s\n", lic.ProductName)
		fmt.Printf("  status:  %s\n", lic.Status)
		fmt.Printf("  due:     %s\n", lic.NextDueDate)
		fmt.Println("\n  Registered and approved. Set this key on an approved lab host.")
		fmt.Println("  Lab use only - never point a production Proxmox host at this proxy.")
		return nil
	},
}

// genProducts and genLevels are the selectable options, with the labels shown
// in the interactive picker. Order is the menu order.
var (
	genProducts = []struct{ code, label string }{
		{"pve", "Proxmox VE"},
		{"pbs", "Proxmox Backup Server"},
		{"pmg", "Proxmox Mail Gateway"},
	}
	genLevels = []struct{ code, label string }{
		{"c", "Community"},
		{"b", "Basic"},
		{"s", "Standard"},
		{"p", "Premium"},
	}
)

// genSockets are the PVE socket counts ([1248] in the key format), in menu order.
var genSockets = []string{"1", "2", "4", "8"}

// resolveGenChoices decides the product, level and (for PVE) socket count for
// `license generate`. An explicit --product / --level / --sockets flag always
// wins. Otherwise, on an interactive terminal, the user picks from a form (same
// style as `setup`); the socket question only appears for PVE, since PVE is the
// only product licensed per socket. Non-interactively it falls back to the
// documented defaults (pve / community / 1 socket) so scripts keep working.
func resolveGenChoices(cmd *cobra.Command) (product, level, sockets string, err error) {
	product, level, sockets = licenseGenProduct, licenseGenLevel, licenseGenSockets
	pickProduct := !cmd.Flags().Changed("product")
	pickLevel := !cmd.Flags().Changed("level")

	if (pickProduct || pickLevel) && interactiveTTY() {
		fields := make([]huh.Field, 0, 2)
		if pickProduct {
			opts := make([]huh.Option[string], len(genProducts))
			for i, p := range genProducts {
				opts[i] = huh.NewOption(fmt.Sprintf("%s (%s)", p.label, p.code), p.code)
			}
			product = genProducts[0].code
			fields = append(fields, huh.NewSelect[string]().
				Title("Which product is this lab key for?").Options(opts...).Value(&product))
		}
		if pickLevel {
			opts := make([]huh.Option[string], len(genLevels))
			for i, l := range genLevels {
				opts[i] = huh.NewOption(fmt.Sprintf("%s (%s)", l.label, l.code), l.code)
			}
			level = genLevels[0].code
			fields = append(fields, huh.NewSelect[string]().
				Title("Subscription level?").Options(opts...).Value(&level))
		}
		if err = huh.NewForm(huh.NewGroup(fields...)).Run(); err != nil {
			return "", "", "", err
		}
	}

	// Non-interactive (or only one side prompted): apply documented defaults.
	if product == "" {
		product = genProducts[0].code
	}
	if level == "" {
		level = genLevels[0].code
	}

	// Sockets only apply to PVE (it is licensed per CPU socket). Ask once the
	// product is known to be PVE; other products ignore the value.
	if product == "pve" {
		if !cmd.Flags().Changed("sockets") && interactiveTTY() {
			sockets = genSockets[0]
			if err = huh.NewForm(huh.NewGroup(
				huh.NewSelect[string]().
					Title("How many CPU sockets? (PVE is licensed per socket)").
					Options(huh.NewOptions(genSockets...)...).Value(&sockets),
			)).Run(); err != nil {
				return "", "", "", err
			}
		}
		if sockets == "" {
			sockets = genSockets[0]
		}
	} else {
		sockets = "" // not encoded in PBS/PMG keys
	}
	return product, level, sockets, nil
}

var licenseListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all subscription keys",
	RunE: func(cmd *cobra.Command, args []string) error {
		licenses, err := store().ListLicenses()
		if err != nil {
			return err
		}
		return render(licenses, func() error {
			if len(licenses) == 0 {
				fmt.Println("no subscriptions yet\nmint a lab key with: proxmox-license-proxy subscription generate")
				return nil
			}
			rows := make([][]string, 0, len(licenses))
			for _, l := range licenses {
				rows = append(rows, []string{l.Key, l.ProductName, string(l.Status), l.NextDueDate})
			}
			printTable([]string{"KEY", "PRODUCT", "STATUS", "DUE"}, rows,
				func(col int, val string) string {
					if col == 2 {
						return colorStatus(val)
					}
					return val
				})
			return nil
		})
	},
}

var licenseShowCmd = &cobra.Command{
	Use:   "show [key]",
	Short: "Show details of a subscription",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		key, err := resolveLicenseKeyArg(args, "show")
		if err != nil {
			return err
		}
		if key == "" {
			return nil
		}
		lic, ok, err := store().GetLicense(key)
		if err != nil {
			return err
		}
		if !ok {
			return fmt.Errorf("subscription %q not found", key)
		}
		return render(lic, func() error {
			fmt.Printf("key:        %s\n", lic.Key)
			fmt.Printf("product:    %s (%s)\n", lic.ProductName, lic.Product)
			fmt.Printf("status:     %s\n", lic.Status)
			fmt.Printf("reg date:   %s\n", lic.RegDate)
			fmt.Printf("due date:   %s\n", lic.NextDueDate)
			return nil
		})
	},
}

var licenseRemoveCmd = &cobra.Command{
	Use:     "rm [key]",
	Aliases: []string{"remove", "delete"},
	Short:   "Remove a subscription key",
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		key, err := resolveLicenseKeyArg(args, "remove")
		if err != nil {
			return err
		}
		if key == "" {
			return nil
		}
		if err := confirm(cmd, licenseRemoveYes, fmt.Sprintf("Remove subscription %q?", key)); err != nil {
			return err
		}
		removed, err := store().RemoveLicense(key)
		if err != nil {
			return err
		}
		if !removed {
			return fmt.Errorf("subscription %q not found", key)
		}
		fmt.Printf("removed %s\n", key)
		return nil
	},
}

var licenseSetDueCmd = &cobra.Command{
	Use:   "set-due [key]",
	Short: "Change the expiry date of a subscription",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		key, err := resolveLicenseKeyArg(args, "re-date")
		if err != nil {
			return err
		}
		if key == "" {
			return nil
		}
		due := licenseSetDue
		if due == "" && interactiveTTY() {
			if err := promptInputValidated("New expiry date (YYYY-MM-DD)", &due,
				func(s string) error {
					_, perr := time.Parse("2006-01-02", s)
					return perr
				}); err != nil {
				return err
			}
		}
		if due == "" {
			return fmt.Errorf("--due is required (YYYY-MM-DD)")
		}
		if _, err := time.Parse("2006-01-02", due); err != nil {
			return fmt.Errorf("--due must be YYYY-MM-DD: %w", err)
		}
		found, err := store().SetDue(key, due)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("subscription %q not found", key)
		}
		fmt.Printf("updated %s due date to %s\n", key, due)
		return nil
	},
}

var licenseExportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export all subscriptions as JSON to a file",
	RunE: func(cmd *cobra.Command, args []string) error {
		licenses, err := store().ListLicenses()
		if err != nil {
			return err
		}
		data, err := json.MarshalIndent(licenses, "", "  ")
		if err != nil {
			return err
		}
		if licenseExportOut == "" {
			fmt.Println(string(data))
			return nil
		}
		if err := os.WriteFile(licenseExportOut, data, 0o600); err != nil {
			return err
		}
		fmt.Printf("exported %d subscriptions to %s\n", len(licenses), licenseExportOut)
		return nil
	},
}

var licenseImportCmd = &cobra.Command{
	Use:   "import",
	Short: "Import subscriptions from a JSON file (upserts by key)",
	RunE: func(cmd *cobra.Command, args []string) error {
		if licenseImportIn == "" && interactiveTTY() {
			if err := promptInput("File to import subscriptions from", "subscriptions.json", &licenseImportIn); err != nil {
				return err
			}
		}
		if licenseImportIn == "" {
			return fmt.Errorf("--in is required")
		}
		data, err := fileio.ReadFile(licenseImportIn)
		if err != nil {
			return err
		}
		var licenses []subscription.License
		if err := json.Unmarshal(data, &licenses); err != nil {
			return fmt.Errorf("parse %s: %w", licenseImportIn, err)
		}
		// Route through the service so the same validation (incl. the mandatory
		// lab signature) applies to imported keys.
		svc := app.New(store())
		for _, lic := range licenses {
			if _, err := svc.AddLicense(app.AddLicenseInput{
				Key:         lic.Key,
				Product:     lic.Product,
				ProductName: lic.ProductName,
				StatusRaw:   string(lic.Status),
				RegDate:     lic.RegDate,
				NextDueDate: lic.NextDueDate,
			}); err != nil {
				return fmt.Errorf("import %s: %w", lic.Key, err)
			}
		}
		fmt.Printf("imported %d subscriptions from %s\n", len(licenses), licenseImportIn)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(licenseCmd)
	licenseCmd.AddCommand(
		licenseAddCmd,
		licenseGenerateCmd,
		licenseListCmd,
		licenseShowCmd,
		licenseRemoveCmd,
		licenseSetDueCmd,
		licenseExportCmd,
		licenseImportCmd,
	)

	licenseAddCmd.Flags().StringVar(&licenseAddProduct, "product", "", "product: pve | pbs | pmg (default: derived from key)")
	licenseAddCmd.Flags().StringVar(&licenseAddName, "name", "", "display product name (default: derived from key)")
	licenseAddCmd.Flags().StringVar(&licenseAddDue, "due", "", "expiry date YYYY-MM-DD (default: +1 year)")
	licenseAddCmd.Flags().StringVar(&licenseAddStatus, "status", "", "initial status (default: APPROVED)")
	licenseAddCmd.Flags().BoolVar(&licenseAddForce, "force", false, "skip key format validation")

	licenseSetDueCmd.Flags().StringVar(&licenseSetDue, "due", "", "new expiry date YYYY-MM-DD")

	licenseRemoveCmd.Flags().BoolVarP(&licenseRemoveYes, "yes", "y", false, "skip confirmation prompt")

	licenseGenerateCmd.Flags().StringVar(&licenseGenProduct, "product", "", "product: pve | pbs | pmg (prompts when omitted on a terminal, else pve)")
	licenseGenerateCmd.Flags().StringVar(&licenseGenLevel, "level", "", "level: c | b | s | p (prompts when omitted on a terminal, else c)")
	licenseGenerateCmd.Flags().StringVar(&licenseGenSockets, "sockets", "", "PVE only: CPU sockets 1 | 2 | 4 | 8 (prompts when omitted on a terminal, else 1)")
	licenseGenerateCmd.Flags().BoolVarP(&licenseGenYes, "yes", "y", false, "skip the lab-only confirmation")
	_ = licenseGenerateCmd.RegisterFlagCompletionFunc("product",
		cobra.FixedCompletions([]string{"pve", "pbs", "pmg"}, cobra.ShellCompDirectiveNoFileComp))
	_ = licenseGenerateCmd.RegisterFlagCompletionFunc("level",
		cobra.FixedCompletions([]string{"c", "b", "s", "p"}, cobra.ShellCompDirectiveNoFileComp))
	_ = licenseGenerateCmd.RegisterFlagCompletionFunc("sockets",
		cobra.FixedCompletions([]string{"1", "2", "4", "8"}, cobra.ShellCompDirectiveNoFileComp))

	licenseExportCmd.Flags().StringVar(&licenseExportOut, "out", "", "output file (default: stdout)")
	licenseImportCmd.Flags().StringVar(&licenseImportIn, "in", "", "input file")

	// Tab completion.
	licenseShowCmd.ValidArgsFunction = completeLicenseKeys
	licenseRemoveCmd.ValidArgsFunction = completeLicenseKeys
	licenseSetDueCmd.ValidArgsFunction = completeLicenseKeys
	_ = licenseAddCmd.RegisterFlagCompletionFunc("status",
		cobra.FixedCompletions([]string{"APPROVED", "PENDING", "BLOCKED"}, cobra.ShellCompDirectiveNoFileComp))
	_ = licenseAddCmd.RegisterFlagCompletionFunc("product",
		cobra.FixedCompletions([]string{"pve", "pbs", "pmg"}, cobra.ShellCompDirectiveNoFileComp))
}
