package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"

	"proxmox-license-proxy/internal/app"
	"proxmox-license-proxy/internal/registry"
	"proxmox-license-proxy/internal/subscription"
)

var (
	licenseAddProduct string
	licenseAddName    string
	licenseAddDue     string
	licenseAddStatus  string
	licenseAddForce   bool

	licenseSetDue string

	licenseExportOut string
	licenseImportIn  string

	licenseRemoveYes bool

	licenseGenProduct string
	licenseGenLevel   string
	licenseGenYes     bool
)

// labLicenseBanner is printed before generating a key to make absolutely sure
// the user understands this is never a production subscription.
const labLicenseBanner = `
============================================================
  ⚠  LAB LICENSE — NOT FOR PRODUCTION
============================================================
  Generated by proxmox-license-proxy for PRIVATE / INTERNAL
  test environments only. This is NOT a real Proxmox
  subscription. Using it on a production host bypasses a
  commercial license.

  Running Proxmox in production? Buy a subscription:
  https://www.proxmox.com
============================================================
`

// store opens the registry store from the loaded settings.
func store() *registry.Store {
	return registry.NewStore(settings.RegistryFile)
}

var licenseCmd = &cobra.Command{
	Use:   "license",
	Short: "Manage license keys in the registry",
}

var licenseAddCmd = &cobra.Command{
	Use:   "add <key>",
	Short: "Add a license key",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		lic, err := app.New(store()).AddLicense(app.AddLicenseInput{
			Key:         args[0],
			Product:     licenseAddProduct,
			ProductName: licenseAddName,
			StatusRaw:   licenseAddStatus,
			NextDueDate: licenseAddDue,
			Force:       licenseAddForce,
		})
		if err != nil {
			return err
		}
		fmt.Printf("added %s (%s, status=%s, due %s)\n", lic.Key, lic.ProductName, lic.Status, lic.NextDueDate)
		return nil
	},
}

var licenseGenerateCmd = &cobra.Command{
	Use:     "generate",
	Aliases: []string{"gen"},
	Short:   "Generate and register a lab-only license key (never for production)",
	Long: "Generate a format-valid Proxmox key that is deliberately marked as a lab key:\n" +
		"the key carries a visible \"1ab\" (lab) signature and its product name is tagged\n" +
		"with the proxmox-license-proxy origin, so its lab status shows in the Proxmox UI.",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Fprint(cmd.OutOrStdout(), labLicenseBanner)
		if err := confirm(cmd, licenseGenYes,
			"I understand this key is LAB-ONLY and must never be used in production. Continue?"); err != nil {
			return err
		}
		lic, err := app.New(store()).GenerateLicense(licenseGenProduct, licenseGenLevel, true)
		if err != nil {
			return err
		}
		fmt.Printf("\n  key:     %s\n", lic.Key)
		fmt.Printf("  product: %s\n", lic.ProductName)
		fmt.Printf("  status:  %s\n", lic.Status)
		fmt.Printf("  due:     %s\n", lic.NextDueDate)
		fmt.Println("\n  Registered and approved. Set this key on an approved lab host.")
		fmt.Println("  ⚠  Lab use only — never point a production Proxmox host at this proxy.")
		return nil
	},
}

var licenseListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all license keys",
	RunE: func(cmd *cobra.Command, args []string) error {
		licenses, err := store().ListLicenses()
		if err != nil {
			return err
		}
		return render(licenses, func() error {
			if len(licenses) == 0 {
				fmt.Println("no licenses")
				return nil
			}
			tw := tabwriter.NewWriter(os.Stdout, 0, 4, 2, ' ', 0)
			fmt.Fprintln(tw, "KEY\tPRODUCT\tSTATUS\tDUE")
			for _, l := range licenses {
				fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n", l.Key, l.ProductName, l.Status, l.NextDueDate)
			}
			return tw.Flush()
		})
	},
}

var licenseShowCmd = &cobra.Command{
	Use:   "show <key>",
	Short: "Show details of a license",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		lic, ok, err := store().GetLicense(args[0])
		if err != nil {
			return err
		}
		if !ok {
			return fmt.Errorf("license %q not found", args[0])
		}
		return render(lic, func() error {
			fmt.Printf("key:        %s\n", lic.Key)
			fmt.Printf("product:    %s (%s)\n", lic.ProductName, lic.Product)
			fmt.Printf("status:     %s\n", lic.Status)
			fmt.Printf("reg date:   %s\n", lic.RegDate)
			fmt.Printf("due date:   %s\n", lic.NextDueDate)
			return nil
		})
	},
}

var licenseRemoveCmd = &cobra.Command{
	Use:     "rm <key>",
	Aliases: []string{"remove", "delete"},
	Short:   "Remove a license key",
	Args:    cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := confirm(cmd, licenseRemoveYes, fmt.Sprintf("Remove license %q?", args[0])); err != nil {
			return err
		}
		removed, err := store().RemoveLicense(args[0])
		if err != nil {
			return err
		}
		if !removed {
			return fmt.Errorf("license %q not found", args[0])
		}
		fmt.Printf("removed %s\n", args[0])
		return nil
	},
}

var licenseSetDueCmd = &cobra.Command{
	Use:   "set-due <key>",
	Short: "Change the expiry date of a license",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		if licenseSetDue == "" {
			return fmt.Errorf("--due is required (YYYY-MM-DD)")
		}
		if _, err := time.Parse("2006-01-02", licenseSetDue); err != nil {
			return fmt.Errorf("--due must be YYYY-MM-DD: %w", err)
		}
		found, err := store().SetDue(args[0], licenseSetDue)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("license %q not found", args[0])
		}
		fmt.Printf("updated %s due date to %s\n", args[0], licenseSetDue)
		return nil
	},
}

var licenseExportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export all licenses as JSON to a file",
	RunE: func(cmd *cobra.Command, args []string) error {
		licenses, err := store().ListLicenses()
		if err != nil {
			return err
		}
		data, err := json.MarshalIndent(licenses, "", "  ")
		if err != nil {
			return err
		}
		if licenseExportOut == "" {
			fmt.Println(string(data))
			return nil
		}
		if err := os.WriteFile(licenseExportOut, data, 0o640); err != nil {
			return err
		}
		fmt.Printf("exported %d licenses to %s\n", len(licenses), licenseExportOut)
		return nil
	},
}

var licenseImportCmd = &cobra.Command{
	Use:   "import",
	Short: "Import licenses from a JSON file (upserts by key)",
	RunE: func(cmd *cobra.Command, args []string) error {
		if licenseImportIn == "" {
			return fmt.Errorf("--in is required")
		}
		data, err := os.ReadFile(licenseImportIn)
		if err != nil {
			return err
		}
		var licenses []subscription.License
		if err := json.Unmarshal(data, &licenses); err != nil {
			return fmt.Errorf("parse %s: %w", licenseImportIn, err)
		}
		// Route through the service so the same validation (incl. the mandatory
		// lab signature) applies to imported keys.
		svc := app.New(store())
		for _, lic := range licenses {
			if _, err := svc.AddLicense(app.AddLicenseInput{
				Key:         lic.Key,
				Product:     lic.Product,
				ProductName: lic.ProductName,
				StatusRaw:   string(lic.Status),
				RegDate:     lic.RegDate,
				NextDueDate: lic.NextDueDate,
			}); err != nil {
				return fmt.Errorf("import %s: %w", lic.Key, err)
			}
		}
		fmt.Printf("imported %d licenses from %s\n", len(licenses), licenseImportIn)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(licenseCmd)
	licenseCmd.AddCommand(
		licenseAddCmd,
		licenseGenerateCmd,
		licenseListCmd,
		licenseShowCmd,
		licenseRemoveCmd,
		licenseSetDueCmd,
		licenseExportCmd,
		licenseImportCmd,
	)

	licenseAddCmd.Flags().StringVar(&licenseAddProduct, "product", "", "product: pve | pbs | pmg (default: derived from key)")
	licenseAddCmd.Flags().StringVar(&licenseAddName, "name", "", "display product name (default: derived from key)")
	licenseAddCmd.Flags().StringVar(&licenseAddDue, "due", "", "expiry date YYYY-MM-DD (default: +1 year)")
	licenseAddCmd.Flags().StringVar(&licenseAddStatus, "status", "", "initial status (default: APPROVED)")
	licenseAddCmd.Flags().BoolVar(&licenseAddForce, "force", false, "skip key format validation")

	licenseSetDueCmd.Flags().StringVar(&licenseSetDue, "due", "", "new expiry date YYYY-MM-DD")

	licenseRemoveCmd.Flags().BoolVarP(&licenseRemoveYes, "yes", "y", false, "skip confirmation prompt")

	licenseGenerateCmd.Flags().StringVar(&licenseGenProduct, "product", "pve", "product: pve | pbs | pmg")
	licenseGenerateCmd.Flags().StringVar(&licenseGenLevel, "level", "c", "level: c (community) | b (basic) | s (standard) | p (premium)")
	licenseGenerateCmd.Flags().BoolVarP(&licenseGenYes, "yes", "y", false, "skip the lab-only confirmation")
	_ = licenseGenerateCmd.RegisterFlagCompletionFunc("product",
		cobra.FixedCompletions([]string{"pve", "pbs", "pmg"}, cobra.ShellCompDirectiveNoFileComp))
	_ = licenseGenerateCmd.RegisterFlagCompletionFunc("level",
		cobra.FixedCompletions([]string{"c", "b", "s", "p"}, cobra.ShellCompDirectiveNoFileComp))

	licenseExportCmd.Flags().StringVar(&licenseExportOut, "out", "", "output file (default: stdout)")
	licenseImportCmd.Flags().StringVar(&licenseImportIn, "in", "", "input file")

	// Tab completion.
	licenseShowCmd.ValidArgsFunction = completeLicenseKeys
	licenseRemoveCmd.ValidArgsFunction = completeLicenseKeys
	licenseSetDueCmd.ValidArgsFunction = completeLicenseKeys
	_ = licenseAddCmd.RegisterFlagCompletionFunc("status",
		cobra.FixedCompletions([]string{"APPROVED", "PENDING", "BLOCKED"}, cobra.ShellCompDirectiveNoFileComp))
	_ = licenseAddCmd.RegisterFlagCompletionFunc("product",
		cobra.FixedCompletions([]string{"pve", "pbs", "pmg"}, cobra.ShellCompDirectiveNoFileComp))
}
