package subscription

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"regexp"
	"strings"
)

// keyRegex matches the real Proxmox subscription key formats, mirroring the
// patterns the Proxmox API enforces so a key we accept is a key Proxmox accepts:
//   - PVE is socket-licensed and encodes a socket count: pve[1248][cbsp]-<10 hex>
//     (e.g. pve1c-0123456789).
//   - PBS and PMG have no socket digit: p(bs|mg)[cbsp]-<10 hex> (e.g. pbsc-0123456789).
var keyRegex = regexp.MustCompile(`^(pve[1248][cbsp]|p(?:bs|mg)[cbsp])-[0-9a-f]{10}$`)

// ValidKey reports whether a key matches the Proxmox format.
func ValidKey(key string) bool { return keyRegex.MatchString(key) }

var productNames = map[string]string{
	"pve": "Proxmox VE",
	"pbs": "Proxmox Backup Server",
	"pmg": "Proxmox Mail Gateway",
}

var levelNames = map[byte]string{
	'c': "Community",
	'b': "Basic",
	's': "Standard",
	'p': "Premium",
}

// LabSignature is embedded at the start of every generated key's hex section so
// a generated key is recognizable at a glance - "1ab" reads as "lab".
const LabSignature = "1ab"

// LabMarker is appended to the product name of generated licenses so the origin
// is visible wherever the subscription is shown (incl. the Proxmox UI).
const LabMarker = "(LAB, proxmox-license-proxy - NOT FOR PRODUCTION)"

var productCodes = map[string]bool{"pve": true, "pbs": true, "pmg": true}

// labSockets is the socket count baked into generated PVE keys. PVE is the only
// product that encodes sockets in the key; lab keys are single-socket.
const labSockets = "1"

// GenerateKey builds a valid but unmistakably lab-marked Proxmox key whose hex
// section starts with the "1ab" signature, e.g. "pve1c-1ab3f9a2c1" (PVE, with
// socket digit) or "pbsc-1ab3f9a2c1" (PBS/PMG). It is a real, format-valid key
// the Proxmox API accepts, yet deliberately NOT a real subscription.
func GenerateKey(product, level string) (string, error) {
	if !productCodes[product] {
		return "", fmt.Errorf("unknown product %q (want pve, pbs or pmg)", product)
	}
	if level == "" {
		level = "c"
	}
	if len(level) != 1 || levelNames[level[0]] == "" {
		return "", fmt.Errorf("unknown level %q (want c, b, s or p)", level)
	}
	buf := make([]byte, 4) // 8 hex chars; we keep 7 after the 3-char signature
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	hexPart := LabSignature + hex.EncodeToString(buf)[:7] // 3 + 7 = 10 hex chars
	prefix := product + level
	if product == "pve" {
		// PVE keys carry a socket-count digit between product and level.
		prefix = product + labSockets + level
	}
	return fmt.Sprintf("%s-%s", prefix, hexPart), nil
}

// IsLabKey reports whether a key was generated by this tool (it carries the lab
// signature at the start of its hex section).
func IsLabKey(key string) bool {
	i := strings.IndexByte(key, '-')
	return i >= 0 && strings.HasPrefix(key[i+1:], LabSignature)
}

// Describe derives the product code, display name and level from a key,
// e.g. "pbsc-..." -> ("pbs", "Proxmox Backup Server Community Subscription", "Community").
// The level letter is the character right before the dash, which keeps working
// whether or not a socket digit sits between product and level (as in PVE keys).
func Describe(key string) (product, productName, level string) {
	i := strings.IndexByte(key, '-')
	if i < 4 {
		return "", "Proxmox Subscription", ""
	}
	product = key[:3]
	name := productNames[product]
	if name == "" {
		name = "Proxmox"
	}
	level = levelNames[key[i-1]]
	return product, strings.TrimSpace(fmt.Sprintf("%s %s Subscription", name, level)), level
}
