package subscription

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"regexp"
	"strings"
)

// keyRegex matches the Proxmox key format: pXX + level letter + 10 hex digits,
// e.g. pbsc-1234567890.
var keyRegex = regexp.MustCompile(`^p(ve|bs|mg)[cbsp]-[0-9a-f]{10}$`)

// ValidKey reports whether a key matches the Proxmox format.
func ValidKey(key string) bool { return keyRegex.MatchString(key) }

var productNames = map[string]string{
	"pve": "Proxmox VE",
	"pbs": "Proxmox Backup Server",
	"pmg": "Proxmox Mail Gateway",
}

var levelNames = map[byte]string{
	'c': "Community",
	'b': "Basic",
	's': "Standard",
	'p': "Premium",
}

// LabSignature is embedded at the start of every generated key's hex section so
// a generated key is recognizable at a glance - "1ab" reads as "lab".
const LabSignature = "1ab"

// LabMarker is appended to the product name of generated licenses so the origin
// is visible wherever the subscription is shown (incl. the Proxmox UI).
const LabMarker = "(LAB, proxmox-license-proxy - NOT FOR PRODUCTION)"

var productCodes = map[string]bool{"pve": true, "pbs": true, "pmg": true}

// GenerateKey builds a valid but unmistakably lab-marked Proxmox key of the form
// p<product><level>-1ab<random>, e.g. "pvec-1ab3f9a2c1". It is a real, format-valid
// key (so the emulation works) that is deliberately NOT a real subscription.
func GenerateKey(product, level string) (string, error) {
	if !productCodes[product] {
		return "", fmt.Errorf("unknown product %q (want pve, pbs or pmg)", product)
	}
	if level == "" {
		level = "c"
	}
	if len(level) != 1 || levelNames[level[0]] == "" {
		return "", fmt.Errorf("unknown level %q (want c, b, s or p)", level)
	}
	buf := make([]byte, 4) // 8 hex chars; we keep 7 after the 3-char signature
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	suffix := hex.EncodeToString(buf)[:7]
	return fmt.Sprintf("%s%s-%s%s", product, level, LabSignature, suffix), nil
}

// IsLabKey reports whether a key was generated by this tool (it carries the lab
// signature at the start of its hex section).
func IsLabKey(key string) bool {
	i := strings.IndexByte(key, '-')
	return i >= 0 && strings.HasPrefix(key[i+1:], LabSignature)
}

// Describe derives the product code, display name and level from a key,
// e.g. "pbsc-..." -> ("pbs", "Proxmox Backup Server Community Subscription", "Community").
func Describe(key string) (product, productName, level string) {
	if len(key) < 4 {
		return "", "Proxmox Subscription", ""
	}
	product = key[:3]
	name := productNames[product]
	if name == "" {
		name = "Proxmox"
	}
	level = levelNames[key[3]]
	return product, strings.TrimSpace(fmt.Sprintf("%s %s Subscription", name, level)), level
}
